### ISSUE TITLE
Update the link to the dropbox

### ISSUE THREAD

**Issue by lichin-lin** [hermy0211/framer30-code#1]
**Description**
Thanks for making all examples able to work both on FramerX and Framer Web👏🏼,
I've checked the hyperlink from the README and it seems GitHub wrap the URL wrong.

I think to make it work, simply change that markdown from `[Dropbox Folder](bit.ly/34GseFx)` to `[Dropbox Folder](https://bit.ly/34GseFx)` can solve the issue.

**Reference**
https://github.community/t5/How-to-use-Git-and-GitHub/Why-is-my-README-hyperlink-going-to-the-wrong-URL/td-p/10710

**Comment by hermy0211** [comment]
Thank you for the heads up! I have updated the link. :)
